spring:
  application:
    name: @name@
    description: @description@
---
info:
  version: @version@
  responsible: Anatoly Cherkasov
  stage: dev
---
management:
  metrics:
    export:
      statsd:
        flavor: etsy
---
server:
  port: @server.port@
